package com.example.bmstu_spotlight.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF534FB1)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF6C69CC)
val onPrimaryContainerLight = Color(0xFFFFFBFF)
val secondaryLight = Color(0xFF5C5A82)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD3D0FE)
val onSecondaryContainerLight = Color(0xFF59587F)
val tertiaryLight = Color(0xFF903B81)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAC549B)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFCF8FF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFFCF8FF)
val onSurfaceLight = Color(0xFF1B1B21)
val surfaceVariantLight = Color(0xFFE4E0F0)
val onSurfaceVariantLight = Color(0xFF474552)
val outlineLight = Color(0xFF777583)
val outlineVariantLight = Color(0xFFC8C5D4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303036)
val inverseOnSurfaceLight = Color(0xFFF3EFF8)
val inversePrimaryLight = Color(0xFFC3C0FF)
val surfaceDimLight = Color(0xFFDCD8E1)
val surfaceBrightLight = Color(0xFFFCF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F2FB)
val surfaceContainerLight = Color(0xFFF0ECF5)
val surfaceContainerHighLight = Color(0xFFEAE7F0)
val surfaceContainerHighestLight = Color(0xFFE5E1EA)


val primaryDark = Color(0xFFC3C0FF)
val onPrimaryDark = Color(0xFF261E83)
val primaryContainerDark = Color(0xFF8885EB)
val onPrimaryContainerDark = Color(0xFF0C005E)
val secondaryDark = Color(0xFFC5C2EF)
val onSecondaryDark = Color(0xFF2D2C51)
val secondaryContainerDark = Color(0xFF444369)
val onSecondaryContainerDark = Color(0xFFB3B1DD)
val tertiaryDark = Color(0xFFFFACEA)
val onTertiaryDark = Color(0xFF5B0852)
val tertiaryContainerDark = Color(0xFFCD70B9)
val onTertiaryContainerDark = Color(0xFF32002D)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131319)
val onBackgroundDark = Color(0xFFE5E1EA)
val surfaceDark = Color(0xFF131319)
val onSurfaceDark = Color(0xFFE5E1EA)
val surfaceVariantDark = Color(0xFF474552)
val onSurfaceVariantDark = Color(0xFFC8C5D4)
val outlineDark = Color(0xFF918F9D)
val outlineVariantDark = Color(0xFF474552)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E1EA)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF5552B4)
val surfaceDimDark = Color(0xFF131319)
val surfaceBrightDark = Color(0xFF39383F)
val surfaceContainerLowestDark = Color(0xFF0E0E14)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F25)
val surfaceContainerHighDark = Color(0xFF2A2930)
val surfaceContainerHighestDark = Color(0xFF35343B)





